apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: ImageStream
    metadata:
      name: jenkins-agent-node12
      namespace: dio-sandbox
      annotations:
        slave-label: node12
      labels:
        role: jenkins-slave
  - apiVersion: v1
    kind: BuildConfig
    metadata:
      name: jenkins-agent-node12
      namespace: dio-sandbox
    spec:
      output:
        to:
          kind: ImageStreamTag
          name: jenkins-agent-node12:latest
      runPolicy: Serial
      source:
        contextDir: agent-nodejs-12
        git:
          uri: 'https://github.com/openshift/jenkins.git'
        type: Git
      strategy:
        dockerStrategy: {}
        type: Docker
      triggers:
        - type: ConfigChange
  - apiVersion: v1
    kind: BuildConfig
    metadata:
      name: nx-tools-example
      namespace: dio-sandbox
    spec:
      runPolicy: Serial
      source:
        git:
          uri: 'git@github.com:abgov/nx-tools-example.git'
        type: Git
      strategy:
        jenkinsPipelineStrategy:
          jenkinsfilePath: .openshift/Jenkinsfile
        type: JenkinsPipeline
