name: e2e

on:
  workflow_dispatch:
    inputs:
      BASE_URL:
        description: Value for --baseUrl in cypress config
        required: true

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: cypress-io/github-action@v2
        with:
          install-command: npm ci
          command: npx nx react-dotnet-example-app-e2e:e2e --dev-server-target='' --baseUrl=${{ github.event.inputs.BASE_URL }}
